default:
	# this one is compiled without any optimzation flags
	gcc -o hello hello.c
	
	# this one is compiled withoptimzation flags
	gcc -Oz -s -o args1 args1.c
	
	# this one is compiled withoptimzation flags
	gcc -Oz -s -o args2 args2.c

clean:
	rm hello.exe args1.exe args2.exe
